# Generated by Django 5.0.3 on 2024-03-14 12:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("booking", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="is_cancelled",
            field=models.BooleanField(default=False),
        ),
    ]
